# Abstract {.unnumbered}

Singular *they* is becoming increasingly common and accepted, but many people find it difficult to learn, instead making seemingly-counterintuitive errors like “she uses they/them pronouns.” Existing pronoun production models argue that speakers select pronouns based on morphosyntactic information associated with a name, or based on semantic/conceptual knowledge about a person. However, learning to use singular *they* may require a change in production processes. The first three experiments argue for a model where speakers may instead need to retrieve information from episodic memory about a person’s stated pronouns or which pronouns other speakers use to refer to them. Experiment 1 establishes a measure for how people learn to associate pronouns with a person, and how they use this information to select which pronouns to produce. Experiment 2 investigates how providing people with information about why paying attention to gendered language is important and how seeing singular *they* modeled can support memory for and production of singular *they*. Experiment 3 moves from written to spoken production, testing how including pronouns on nametags and in introductions---common EDI recommendations---affects pronoun choice. Experiment 4 investigates online comprehension, using the visual world paradigm to characterize how singular *they* is being integrated into existing processing mechanisms. The results demonstrate that people can learn that someone uses they/them after only brief introductions, and that a PSA, including pronouns on nametags, and including pronouns in introductions can support accurate production of singular *they*. These findings help extend processing models to account for a wider range of people’s language use and contribute to evidence-based best practices for creating gender-inclusive environments.