---
subtitle: "<b>The State of Singular <i>They</i></b>"
toc-title: "Introduction"
toc-expand: 1
---

# Introduction {#introduction .unnumbered}

## 0.1 Overview {#overview}

As the use of they/them pronouns becomes more common and more accepted, an increasing number of speakers find themselves making seemingly paradoxical errors, such as in the following headline:

::: {#exm-lovato .example-formatting}
\
Demi Lovato~i~ thanks Lizzo for correcting paparazzo who misgendered her~i~: "I love you."\
The "Dancing With The Devil" singer~i~ came out as nonbinary in May and goes by "they/them" pronouns.\
--- *Entertainment Weekly* [@towers2021]
:::

The article describes a press interview where Lizzo corrects paparazzi misgendering Lovato. In the quoted exchange, Lizzo is asked a question about collaborating with Lovato that uses she/her to refer to Lovato. Lizzo corrects this, the question is repeated still using she/her, and Lizzo states twice more that Lovato uses they/them. Although the paparazzi did not change their pronoun use in this conversation, Lovato was grateful for the support. Despite the article being about misgendering and they/them pronouns, the author does not consistently use they/them to refer to Lovato. However, it is unlikely that the author entirely refuses to use singular *they* or the publication prohibits it, as several references to Lovato in the middle of the article are correct. Instead, the author appears to not have noticed the alternations between she/her and they/them, despite the context making accurate use of they/them pronouns as salient as possible, and despite good intentions.

One of the starting questions of this dissertation is *why do people do this?* Why are errors like "she uses they/them pronouns" common, where the speaker knows that a particular person uses they/them, recalls it in the conversational context, and expresses support for that person's identity, but still produces *she* instead of *they* when referring to them? The growing support for and familiarity with singular *they* during the past few years suggests that many people are open to learning [@minkin2021; @parker2019], and that a substantial part of the barrier causing frequent misgendering comes from lower-level language processes for producing pronouns, as opposed to higher-level attitudes about gender and language.

In addition to learning that the grammatical representation of *they* allows it to corefer with specific singular referents (i.e., proper names), the learning process may require a change from accessing a person's pronoun (*he* or *she*) based on semantic/conceptual features of a person [e.g., @anton-mendez2010], or based on morphosyntactic gender marking associated with a person's name [e.g., @schmitt1999]. The first three experiments argue for a model where, in order to use singular *they* correctly, speakers may instead need to retrieve information from episodic memory about a person's stated pronouns or which pronouns other speakers use to refer to them. Experiment 1 establishes a measure for how people learn to associate pronouns with a person, and how they use this information to select which pronouns to produce. Experiment 2 investigates how providing people with information about why paying attention to gendered language is important and how seeing singular *they* modeled can support memory for and production of they/them pronouns. Experiment 3 moves from written to spoken production, testing how including pronouns on nametags and in introductions---common EDI recommendations---affects pronoun choice. Finally, Experiment 4 investigates online comprehension, using the visual world paradigm to characterize the processing of they coreferring with proper names. Before that, the remainder of this introduction reviews terminology about coreference and gender; prior research about the acceptability, comprehension, and production of singular *they*; and the sociopolitical context of misgendering.

## 0.2 Terminology {#terms}

### 0.2.1 Coreference {#coreference}

In conversations and writing, we use a variety of expressions to refer to the same entity, and keeping track of this---doing [coreference resolution]{#def-coreference .link-primary title="definition: coreference"}---is one of the core problems of language comprehension [@cornish2006; @garnham2006; @huang2006]. When talking about people, speakers have the choice between proper names (*Bethany, Bethany Gardner*), pronouns (*they, she*), role nouns (*the author*), and other noun phrase descriptions (*the author of this dissertation*). Comprehenders have to identify who is being talked about when a person is first mentioned, then match later referring expressions back to that [referent]{#def-referent .link-primary title="definition: referent"}. Pronouns nearly always refer to someone mentioned previously---an [antecedent]{#def-antecedent .link-primary title="definition: antecedent"}---instead of introducing a new referent [@kennison2009]. However, in many contexts there are multiple possible antecedents for the same pronoun, and understanding how comprehenders successfully manage this has been the focus of decades of psycholinguistics research. As a brief summary, one class of theories argues that comprehenders identify the referent based on which entities are currently "centered" in attention, which is determined primarily based on grammatical roles (e.g., the subject of the sentence) and information structure (e.g., topic changes) [@gordon1993; @grosz1986; @joshi2006; @walker2002]. The second major class of theories, coherence-driven approaches, argues that coreference resolution is a consequence of broader inferential reasoning using world knowledge to construct an interpretation of the conversation as a whole [@greene1992; @mckoon1996]. While centering and coherence approaches have generally been considered mutually exclusive, one way of reconciling them is a probabilistic model where comprehenders are using coherence-driven expectations about what entities the speaker will refer to next, and speakers are using centering-driven likelihoods to choose referential forms [@kehler2013]. Aside from the terminology used for reference resolution, the key takeaway for the rest of this dissertation is that coreference---even for neutral, established, uncontroversial pronouns like *he* and *she*---is complicated.

### 0.2.2 Gender in Linguistics {#gender-linguistics}

In a linguistics context, *gender* can refer to multiple concepts: grammatical, conceptual, and social. First, [grammatical gender]{#def-grammatical-gender .link-primary title="definition: grammatical gender"} refers to linguistic features. Languages with grammatical gender systems (e.g., Spanish, French, and German) classify nouns by gender; and determiners, pronouns, and adjectives have morphosyntactic features that mark agreement with the noun's gender [@gygax2019]. For example, *book* is a masculine noun in Spanish (*libro~[MASC]{.smallcaps}~*), so the masculine forms of determiners are used (e.g., *el~[MASC]{.smallcaps}~* instead of *la~[FEM]{.smallcaps}~*) and adjectives are conjugated with the masculine ending (e.g., *nuevo~[MASC]{.smallcaps}~* instead of *nueva~[FEM]{.smallcaps}~*), resulting in phrases like *el~[MASC]{.smallcaps}~ libro~[MASC]{.smallcaps}~ nuevo~[MASC]{.smallcaps}~* for *the new book*. Here, *gender* means something more like *kind* or *class*, and while many grammatical gender languages label the classes as masculine, feminine, and neutral, some languages have more than two or three genders [@corbett2013a]. Most gender classifications of nouns in grammatical gender languages are clearly arbitrary---there is nothing about a book that makes it masculine or feminine. Instead, grammatical gender can be thought of as a component of the word's structure, not its meaning [@anton-mendez2002; @wang2019].

Languages without grammatical gender, such as English, are typically referred to as natural gender languages. Natural gender languages do not group nouns into gender classes, but many do mark gender for pronouns referring to people [@gygax2019; @siewierska2013]. Gender marking of pronouns in natural gender languages is so-called because it is assumed to reflect inherent biological categories (e.g., @corbett2013b; critiqued by @mcconnell-ginet2014). This becomes a problem if you acknowledge that gender (and to some degree, biological sex) is a social construction with the potential to have more than two binary categories. With regard to pronouns, a better explanation---in terms of gender theory as well as simply explaining linguistic behavior---is to treat pronouns as reflecting a shared social understanding, instead of an ontological or biological claim (@conrod2019, discussed in more detail later in [Section 0.5](#production "Production")). With regard to nouns, instead of calling this natural gender, I refer to this as [conceptual gender]{#def-conceptual-gender .link-primary title="definition: conceptual gender"}, following @ackerman2019.

In addition to accounting for modern concepts of [social gender]{#def-social-gender .link-primary title="definition: social gender"}, decoupling gendered language from claims about inherent natural categories also facilitates making distinctions between two different ways that nouns can carry conceptual gender information, which become relevant in psycholinguistics experiments. In [definitionally-gendered]{#def-definitional-gender .link-primary title="definition: definitional gender"} nouns, the gender information is part of the meaning itself, e.g., *son* or *queen*. In [stereotypically-gendered]{#def-stereotypical-gender .link-primary title="definition: stereotypical gender"} nouns, gender information is part of our knowledge about gender stereotypes, distributions, and expectations, e.g., *mechanic* or *nurse*. Even if they do not believe this should be the case, people know that being a mechanic fits better into expectations for men and being a nurse fits better into expectations for women, and that people employed as mechanics are more likely to be men and people employed as nurses are more likely to be women. Similarly, English first names carry probabilistic information about gender. When talking about names for the design of the experiments in this dissertation, I refer to people's knowledge about gender associations of a name (i.e., that most people named *Mary* are women, or that people named *Jordan* are commonly men or women).[^0_introduction-1]

[^0_introduction-1]: See @bjorkman2017 and @konnelly2020 for a discussion of how proper names may have morphosyntactic gender features used to evaluate agreement with pronouns, a question that this dissertation remains agnostic about.

Part of [coreference resolution](#def-coreference) requires evaluating whether a potential [antecedent](#def-antecedent) matches the pronoun for features including gender and number. Which aspect(s) of gender, precisely, are being evaluated? Grammatical, conceptual, or social? Since modern English does not have grammatical gender, @ackerman2019 argues that we are using conceptual gender (see @sato2013 for similar empirical findings). In order to distinguish how grammatical, conceptual, and social gender may be cognitively and linguistically encoded, Ackerman presents a three-tier model of gender agreement. The exemplar tier represents knowledge about our experiences with cues about gender, including the gender associations of first names, clothing and hair styles, vocal pitch, and other speech characteristics indexed as masculine or feminine. The distribution on the exemplar tier is strongly bimodal for most people, but would change as someone gains more experience with gender-nonconforming and [nonbinary](#def-nonbinary) people. The category tier represents our cognitive categorizations about gender, conceptualized as two discrete, non-overlapping categories laid over the bimodal distribution of the exemplar tier. Children develop categories for gender early on, and people automatically categorize others as male or female, regardless of whether these inferences are accurate or necessary [@bussey1999; @fagot1993; @friedman2014; @martin2002; @martin2004; @waxman2010]. This tendency in language comprehension is discussed later in [Section 0.4.1](#production "Processing Gender Agreement"). Finally, the feature tier represents labels and grammatical features associated with the categories on the category tier. In summary, being precise about what we mean when we say *conceptual gender* requires making distinctions between the knowledge and experiences we use to make gender inferences, the categories we infer from that knowledge and experience, and the labels we assign to those categories.

### 0.2.3 Forms of Singular *They* {#they-forms}

Forms of singular *they* vary in three primary aspects---definiteness, specificity, and gender information---and the usage becomes more contested as [referents](#def-referent) become more definite, specific, and gender-known [@bjorkman2017; @conrod2019; @konnelly2020]. Broadly speaking, [definite]{#def-definite .link-primary title="definition: definite referents"} forms, including proper names and noun phrases with *the*, allow the comprehender to identify a referent; [indefinite]{#def-indefinite .link-primary title="definition: indefinite referents"} forms, including noun phrases with *a/an*, do not [@abbott2006]. [Generic]{#def-generic .link-primary title="definition: generic referents"} forms refer to a group of people, while [specific]{#def-specific .link-primary title="definition: specific referents"} forms refer to an individual [@carlson2006; @farkas2006; @fodor1982]. Definiteness and specificity are distinct features here, since expressions can be specific but indefinite---referring to one referent within a group, but not specifying which one.

The oldest and most common form of singular *they* is the [generic indefinite]{#def-generic-indefinite .link-primary title="definition: generic indefinite singular they"}:

::: {#exm-shakespeare .example-formatting}
\
There's not a man~i~ I meet but doth salute me\
As if I were their~i~ well-acquainted friend\
--- *A Comedy of Errors* [@shakespeare1623]
:::

::: {#exm-austen .example-formatting}
\
Everybody~i~ was punctual, everybody~i~ in their~i~ best looks: not a tear, and hardly a long face to be seen.\
--- *Emma* [@austen1815]
:::

This form dates back to late Middle English, with some of the earliest examples appearing in Chaucer's *Canterbury Tales*, and has been in continuous use since then [@balhorn2004; @baskervill1895; @oedonline2021]. In the 18th century, prescriptive grammarians started pushing for the exclusive use of *he* as a generic [@bodine1975], which I discuss more in [Section 0.8](#sociopolitical-context "Sociopolitical Context"). Currently, generic indefinite singular *they* is widely accepted [@hekanaho2020]. The majority of style guides allow it, but still recommend using the phrase *he or she* or rephrasing the sentence to be plural [@robertson2021].

Compared to the generic indefinite, [specific definite]{#def-specific-definite .link-primary title="definition: specific definite singular they"} forms of singular *they* show much more variation in acceptability and frequency. It can be used in several [gender-unspecified]{#def-gender-unspecified .link-primary title="definition: gender-unspecified singular they"} contexts, such as when the speaker does not know the referent's gender. This context implies that the referent's gender is unknown, not necessarily that they are nonbinary or use they/them pronouns [@conrod2019]. The other speaker can add more information, either directly as in @exm-tma1, or indirectly through modeling pronoun use in a subsequent utterance.

::: {#exm-tma1 .example-formatting}
\
A: Oh, okay, okay, um...What---Would you mind telling me what happened? Uh, what they~i~ did?\
B: He~i~.\
A: Did he~i~ look like he~i~ hadn't slept in about a week?\
--- *The Magnus Archives*, pre-scripted podcast [@sims2019]
:::

Typically, if information about the referent's gender becomes available, speakers will switch to using *he* or *she*. The primary variance I observe is whether people hedge an unknown with *they*, or make a potentially incorrect guess with *he* or *she*. This form is also used in contexts where the speaker knows the gender of the referent and the addressee does not, but the speaker does not include that information. This seems to be most common when referring to people by relationships or contexts instead of by name, since the addressee does not know them (e.g., *my friend from undergrad*). @exm-bright-sessions shows a conversation where Speaker B interprets Speaker A's use of singular *they* as gender-unspecified. When Speaker A introduces the referent's name, Speaker B uses this information to switch from gender-unspecified *they* to specifying *he*. Speaker A then has to clarify that they had meant gender-specified *they*, where the referent uses they/them not he/him:

::: {#exm-bright-sessions .example-formatting}
\
A: A friend~i~ of mine...they've~i~ sort of dropped off the face of the earth and I'm worried about them~i~. I wouldn't normally go this crazy about this, but I wanted to make sure they're~i~ alright. I just have a weird feeling about it all.\
B: What's their~i~ name?\
A: Ben~i~. Ben Bernard~i~.\
B: Put your number in and I'll let you know if I find him~i~.\
A: Them~i~.\
B: Got it, great.\
--- *The College Tapes*, pre-scripted podcast [@snow2021]
:::

The specific, definite, and [gender-specified]{#def-gender-specified .link-primary title="definition: gender-specified singular they"} form of singular *they*---the context described by "using they/them pronouns"---is the newest and most contested form. Although English first names do not carry definitive gender information, most carry strong probabilistic information and are perceived as gendered. Singular *they* coreferring with a proper name is carrying information about the referent's gender, not leaving it unspecified, e.g.:

::: {#exm-atlantic .example-formatting}
\
Howell~i~ is about to graduate from college, and finding the perfect job isn't necessarily their~i~ top priority. They're~i~ thinking holistically about community, joy, and fulfillment. They~i~ are also looking beyond their~i~ 20s.\
--- "The one-size-fits-all narrative of your 20s needs to change," *The Atlantic* [@stauffer2021]
:::

::: {#exm-tma2 .example-formatting}
\
Without warning, Francis~i~ kicks their~i~ free leg against the table. It does not move...Their~i~ chest rises and falls rapidly as they~i~ are lowered into the only seat, the dusty air of the theater scratching their~i~ throat and drying their~i~ mouth.\
--- *The Magnus Archives*, pre-scripted podcast [@sims2020]
:::

::: {#exm-ballet .example-formatting}
\
With my work I think you definitely know the male figure~i~ is isolated, um, feels unaccepted, feels, uh, um, just that they~i~ have no identity.\
--- "Other Voices: Matthew Neenan," video interview [@nashvilleballet2020]
:::

Singular *they* coreferring with [definitionally-gendered](#def-definitional-gender) role nouns behaves similarly (see @bjorkman2017; @konnelly2020). However, these usages are less common, likely because people who use they/them pronouns often also prefer gender-neutral titles (e.g., *Mx*) and role nouns (e.g., *sibling*) [@cassian2021; @cassian2022]. Cases where the speaker unambiguously marks gender in one form of reference but not in pronouns do occur, such as @exm-ballet. This usage is not as relevant to the current questions, since speakers are rarely asked to produce it, but what discourse factors cause speakers to spontaneously produce it is a question for future research.

### 0.2.4 LGBTQ Identity {#lgbtq}

Here, I use [trans and gender diverse (TGD)]{#def-TGD .link-primary title="definition: trans and gender diverse"} as an umbrella term for anyone whose gender is different than their [sex assigned at birth]{#def-SAB .link-primary title="definition: sex assigned at birth"} (what was put on their birth certificate) and [cisgender]{#def-cis .link-primary title="definition: cisgender"} as an umbrella term for anyone whose gender matches their sex assigned at birth. People use a variety of terms to describe their identities, which currently include *transgender, nonbinary, genderqueer, genderfluid, gender non-conforming*, and *queer* [@cassian2021; @cassian2022; @glaad2020; @harrison2012; @james2016; @kuper2012]. Currently, [nonbinary]{#def-nonbinary .link-primary title="definition: nonbinary"} is the most common label for people whose gender is not entirely within the categories of male or female, some of whom also identify as trans [@cassian2021; @cassian2022; @glaad2020; @james2016; @wilson2021]. While many nonbinary people use they/them pronouns, not all do, and not all people who use they/them are nonbinary. Pronouns are one of the cues we use to convey gender, and they strongly correlate with gender identity, but the mapping is not a one-to-one rule. Because of this, I specify "people who use they/them pronouns" instead of "nonbinary people" or "nonbinary pronouns." Otherwise, when describing prior research findings, I use the authors' terminology, noting that variations in the language used to recruit and describe participants select for different subsets of the TGD community.

## 0.3 Acceptability and Grammaticality {#acceptability}

Much of the recent linguistics research on singular *they* has focused on acceptability and grammaticality judgments. People's acceptability judgments tend to fall into one of three patterns: "Non-innovators" only accept [generic](#def-generic "generic singular they") [antecedents](#def-antecedent "antecedent") for singular *they* (e.g., *each person, everyone*) and do not accept any [specific](#def-specific "specific singular they") antecedents. In addition to generic antecedents, "innovators" accept specific, but only [gender-unspecified](#def-gender-unspecified "gender-unspecified singular they") antecedents for singular *they* (e.g., *my friend*). To accommodate proper names, "innovative" speakers can add a new version of the name to their linguistic knowledge that is not grammatically marked as masculine or feminine. This means that they can accept singular *they* for a person that they have learned uses they/them pronouns, but implies that it occurs through an exception to their gender agreement system, not a change to it. Finally, "super-innovators" accept any singular antecedents for *they*, including [gender-specified](#def-gender-specified "gender-specified singular they") ones (e.g., [definitionally-gendered](#def-definitional-gender) nouns like *sister*, any proper names) [@bjorkman2017; @camilliere2021; @konnelly2020].

Several factors have been repeatedly demonstrated to correlate with acceptability judgments. People who are younger [@conrod2019; @hekanaho2020; @parker2019], who are LGBTQ+ [@hernandez2020; @nichols2019], and who know [trans and gender diverse](#def-TGD "TGD") people [@ackerman2017; @hekanaho2020] consider singular *they* more acceptable. Attitudes about gender play a role: unsurprisingly, people who express more support of TGD people are more likely to consider singular *they* acceptable [@hekanaho2020; @hernandez2020]. Benevolent sexism, which measures endorsement of traditional gender roles and belief in binary gender essentialism, is negatively correlated with acceptability ratings; but hostile sexism, which measures overt hostility towards women, has not been shown to be related [@bradley2020].

Beliefs about grammar and language change are among the most commonly cited metalinguistic reasons for disliking singular *they* [@bodine1975; @hekanaho2020]. People who strongly endorse linguistic prescriptivism, which values "correct" language use and opposes changes to this standard, rate singular *they* as less acceptable [@bradley2020]. Conversely, support of non-sexist language reform, which often focuses on avoiding masculine forms as the [generic](#def-generic "generic") or the default, predicts higher acceptance of singular *they* [@hekanaho2020]. Notably, predictors of attitudes about singular *they* now are similar to predictors of attitudes about non-sexist language reform in the 1980s and 1990s. Alternatives to using *he* as the generic include phrases like *he/she* and *he or she*, as well as using singular *they* or *she* as a generic. People who were younger, who agreed that despite advances in equality women still face less-overt forms of sexism [@swim1995], and who had less conservative views about gender roles were more likely to support non-sexist language reform [@jacobson1985; @mcminn1990; @parks2004; @parks2008; @rubin1994; @sarrasin2012; @swim2004]. I return to discussing the similarities between these two debates later in [Section 0.8](#sociopolitical-context "Sociopolitical Context"). While language attitudes certainly play a role, they do not explain all---or even, arguably, the majority---of variance in acceptability judgments about singular *they*. While the acceptability of generic, gender-unspecified forms of singular *they* was predicted by both linguistic prescriptivism and anti-trans prejudice, the acceptability of specific, gendered forms (e.g., coreferring with names) was primarily predicted by anti-trans prejudice [@hernandez2020].

Many of the predictors of attitudes about singular *they* are highly correlated. For example, people who are younger are more likely to be exposed to singular *they*, to know a TGD person, and to have less conservative beliefs about gender and sexuality [@minkin2021; @parker2019]. It is still unclear whether age predicts attitudes towards singular *they* primarily by proxy through these other social factors, or if age-related differences in language learning and processing [@dede2016] are also at play. Some preliminary research has begun to try to tease these apart. @kramer2021, for example, argues that experience is a better predictor of using they/them pronouns correctly than age. Overall, the relationship between these predictors is still unclear and remains an area for future research.

## 0.4 Comprehension {#comprehension}

Turning to comprehension, research has examined both [offline comprehension]{#def-offline .link-primary title="definition: offline comprehension"}---asking people about their interpretation of a sentence *after* reading or listening to it---and [online comprehension]{#def-online .link-primary title="definition: online comprehension"}---using measures such as reading time or eye gaze to observe people's interpretation of a sentence *while* reading or listening to it [@allopenna1998; @liversedge2000; @tanenhaus1995; @tanenhaus2000]. Most studies of reading use one of two paradigms. In [self-paced reading]{#def-SPR .link-primary title="definition: self-paced reading"} tasks, participants press a button to advance through the text one phrase or word at a time, measuring how long they spend at each region. In [eyetracking while reading]{#def-eyetracking-reading .link-primary title="definition: eyetracking while reading"} tasks, participants' eye movements are recorded while they read (relatively) naturalistically, measuring the sequence and duration of their [saccades]{#def-saccade .link-primary title="definition: saccade"} to (eye movements directed towards) and [fixations]{#def-fixation .link-primary title="definition: fixation"} on (gaze focused on) each word or phrase [@liversedge1998; @rayner2006]. Generally, longer durations at and regressions back to a region are assumed to reflect having more difficulty understanding the text [@carpenter1983; @henderson2013; @rayner1988]. This is referred to as a [processing cost]{#def-cost .link-primary title="definition: processing cost"} or penalty. The following section is organized using the same three categories of singular *they* as [Section 0.2.3](#they-forms "Forms of Singular They"): generic indefinite, specific definite gender-unspecified, and specific definite gender-specified (i.e., coreferring with proper names). But before discussing the existing research about comprehending singular *they*, I first review the prior research on gender agreement processing that it is based on.

### 0.4.1 Processing Gender Agreement {#gender-agreement}

The majority of studies about gender agreement have used [stereotype mismatch tasks]{#def-stereotype-mismatch .link-primary title="definition: stereotype mismatch task"}, classically illustrated with:

::: {#exm-surgeon-riddle .example-formatting}
\
A man and his son were away for a trip. They were driving along the highway when they had a terrible accident. The man was killed outright but the son was alive, although badly injured. The son was rushed to the hospital and was to have an emergency operation. On entering the operating theatre, the surgeon looked at the boy, and said, "I can't do this operation. This boy is my son." How can this be? [@sanford1985]
:::

Many readers are confused by this story (see @morehouse2022 for a more recent overview). If, following the gender stereotype, the surgeon was assumed to be male, how could the boy's father be both dead in the accident and working at the hospital? It takes time to come to the correct interpretation, that the surgeon is the boy's mother. In the basic mismatch paradigm, participants read a sentence where a character is first referred to by a [stereotypically-gendered](#def-stereotypical-gender) role noun (usually a profession) and later referred to with a pronoun that matches or mismatches the stereotype. Stereotype-mismatching pronouns (e.g., *surgeon...she*) take longer to read than stereotype-matching pronouns (e.g., *surgeon...he*), suggesting that when readers had first encountered the new [referent](#def-referent), they used gender stereotype information to make an inference about the referent's gender [@kennison2003; @reynolds2006]. Upon reaching the mismatching pronoun, readers have to revise their interpretation, which incurs a processing cost. Alternatively, if a gender inference had not been made at the role noun, the process of making a gender inference at the pronoun would be the same regardless of stereotype match.

Converging evidence is also available from event-related potential [(ERP)]{#def-ERP .link-primary title="definition: ERP"} data, which uses electrodes placed on the scalp to measure changes in the brain's electrical field caused by neural activity [@samar2006]. Stereotype-mismatching pronouns elicit a [P600 effect]{#def-P600 .link-primary title="definition: P600 effect"}: a positive wave in the centro-parietal regions, occurring 600--100ms after the word [@friederici2002]. Some argue that the P600 indexes syntactic processing, and it can be observed when listeners encounter a syntactic error, a sentence with a complex syntactic structure, or new information that requires revising their interpretation of the sentence's syntactic structure [@hagoort1993; @kaan2000; @osterhout1994; @osterhout1992]. Like a longer reading time, a P600 is interpreted as indicating that the sentence's syntactic structure is harder to understand. Notably, the P600 effect was still observed when participants judged the sentences with stereotype-mismatching pronouns to be acceptable [@osterhout1997; see @banaji1996; @oakhill2005 for similar findings in a priming paradigm]. Generally, the mismatch paradigm tends to remain agnostic about whether the mismatch effect arises more from gender stereotype beliefs or more from distributional knowledge. However, the fact that it occurs in the absence of negative metalinguistic judgments can be interpreted in favor of the gender mismatch being more due to statistical expectations in language processing (i.e., that *surgeon* occurs more frequently with *he* than *she*) than to higher-level beliefs about gender (i.e., that surgeons should be men).

[Grammatical gender](#def-grammatical-gender) languages provide stronger evidence for early, automatic inferences about the gender of referents when they are introduced into the discourse context. @carreiras1996 compared English results to Spanish, which marks gender on determiners and nouns. In English, the role noun provides stereotype information, and the referent's gender is not specified until the pronoun; in Spanish, the referent's gender is specified at the determiner:

::: {#exm-carreiras1 .example-formatting}
\
1 The footballer wanted to play in the match.\
2 He~[MASC]{.smallcaps}~/She~[FEM]{.smallcaps}~ had been training very hard during the week.
:::

::: {#exm-carreiras2 .example-formatting}
\
1 El~[MASC]{.smallcaps}~ futbolista/La~[FEM]{.smallcaps}~ futbolista quería jugar el partido.\
2 El~[MASC]{.smallcaps}~/Ella~[FEM]{.smallcaps}~ había estado entrenando mucho durante la semana.
:::

Because the determiner is gender-marked in Spanish (@exm-carreiras2), the referent's gender is disambiguated from the beginning. English (@exm-carreiras1) allows readers to make a guess about gender at the beginning using their knowledge about the gender-stereotyped role noun, but does not disambiguate the referent's gender until the pronoun in the second sentence, making it possible to have an incorrect interpretation of the referent's gender during the first sentence. Both English and Spanish showed a mismatch effect, where stereotype-mismatching sentences (*footballer...she* in [-@exm-carreiras1]) took longer to read than stereotype-matching sentences (*footballer...he* in [-@exm-carreiras1]), but it occurred at different points in the story. While English showed the mismatch effect at the pronoun (sentence 2 in [-@exm-carreiras1]), Spanish showed the mismatch effect at the role noun (sentence 1 in [-@exm-carreiras2]). This indicates that readers made inferences about the referent's gender as soon as gender information became available, regardless of whether or not it was necessary for comprehension.

An alternative explanation to these results, at least in English, is that the gender stereotype of the role noun is only activated when the pronoun is read, not when the role noun first introduces the referent. Thus, the slowdown would come only from incongruent gender cues, not from needing to revise an initial interpretation. In Examples [-@exm-carreiras1] and [-@exm-carreiras2], this explanation would look like taking longer to process she coreferring with footballer because it does not match gender stereotype predictions, but not because the footballer had been interpreted as male in the prior sentence. To rule out this explanation, @garnham2002 tested the mismatch effect with two probabilistic cues about gender: role nouns and either gendered clothing or physical traits:

::: {#exm-garnham .example-formatting}
\
1 The housekeeper/soldier\
2 was rushed to the hospital, taken to a private ward, and\
3 gave birth half an hour later.
:::

Here, both the role noun and the verb are stereotypically gendered, compared to prior experiments that paired a [stereotypically-gendered](#def-stereotypical-gender "stereotypical gender") role noun with a [definitionally-gendered](#def-definitional-gender "definitional gender") pronoun.[^0_introduction-2] A mismatch effect will only occur if inferences about the referent's gender are made at both the role noun (line 1 in [-@exm-garnham]) and at the stereotypically-gendered verb (line 3 in [-@exm-garnham]), not just at the verb. In other words, *the soldier...gave birth* would not take longer to read than *the housekeeper...gave birth* unless the reader had already inferred that the soldier was male before reaching *gave birth*. Results showed mismatch effects for reading time and acceptability judgment reaction times, which indicates that definitionally-gendered language is not necessary to assign a gender to referents. Instead, comprehenders use probabilistic information such as gender stereotype and distributional knowledge about role nouns to make an inference about the referent's gender. This inference may be proven wrong after encountering further information, and needing to revise an interpretation of a referent who has been represented as (probably) one gender incurs a [processing cost](#def-cost).

[^0_introduction-2]: Arguably, pronouns are not definitionally gendered, since not all people who use she/her are women and not all women use she/her, and vice versa for men and he/him. However, treating pronouns as probabilistic cues---nearly all people who use she/her are women and nearly all women use she/her---would make the same predictions. Even if it is not a binary rule, the pronoun would still be a stronger cue about gender than the stereotypes associated with a role noun.

Another benefit of using [grammatical gender](#def-grammatical-gender) languages to study agreement processing is that they allow grammatical and [social gender](#def-social-gender) cues to be manipulated separately, potentially providing conflicting information [@reali2015]. Results from multiple languages suggest that stereotypical knowledge is activated independently from morphosyntactic cues [@molinaro2016; @schmitt2002]. In addition to integrating potentially-conflicting gender cues, gender inferences need to be integrated with other cues about reference. Having the prior context indicate the gender of the referent eliminates the mismatch effect [@duffy2004; @kreiner2008]:

::: {#exm-duffy-keir .example-formatting}
\
1 Jeff's/Lucy's power had been unreliable ever since the tornado. The electrician was a cautious man/woman who carefully secured his/her ladder to the side of the house before checking the roof. Jeff/Lucy suspected that high winds had loosened the connection to the power lines.\
2 The electrician taught himself/herself a lot while fixing the problem.
:::

While the pronoun (*herself*) does mismatch the stereotypical role noun (*electrician*), it does not mismatch the interpretation supported by the preceding context (*the electrician was a cautious woman*). In stories like @exm-duffy-keir, *herself* does not take longer to read than *himself*, like it would if the second part were read in isolation. This does not imply that no difficulty integrating unexpected information happens, only that this process has already occurred before reaching the pronoun.

Gender information also interacts with broader discourse expectations. In English, pronouns are more likely to corefer with previously-mentioned names than upcoming new names. Participants took longer to reject gender-mismatching interpretations when a cue separate from gender---order of mention---supported the gender-mismatching interpretation (e.g., *John...she*) than when the order cue did not support the gender-mismatching interpretation either (e.g., *she...John*) [@kennison2009]. Most of the studies discussed have presented stereotypical gender information when first introducing the referent, but stereotypical gender cues can also be used to revise prior interpretations made using other cues, such as order [@pyykkonen2010].

Even when it is a highly salient cue, gender information is not necessarily applied symmetrically. One experiment in German, aiming to distinguish between grammatical gender and stereotypical gender cues, measured reading times for pronouns in passages that described stereotypically-gendered jobs without using the grammatically-gendered role noun itself:

::: {#exm-german .example-formatting}
\
Original: L.K. vereinbart Termine, erledigt die Korrespondenz in einem Büro. Außerdem kann er eine fremde Sprache.\
Translated, maintaining the German word order: L.K. makes appointments, deals with the correspondence in an office. In addition speaks he a foreign language.
:::

The mismatch effects for masculine pronouns coreferring with feminine jobs and for feminine pronouns coreferring with masculine jobs were different. In examples such as [-@exm-german], masculine pronouns in a feminine context caused readers to look at the masculine pronoun for longer and to be more likely to look back at it, indicating that the gender mismatch effect occurred during both early and late stages of processing. In contrast, feminine pronouns in masculine contexts did elicit a mismatch effect, but only during late stages of processing. While female referents were interpreted to be compatible with both masculine and feminine contexts, male referents were only compatible with masculine contexts [@reali2015]. This suggests that in the absence of definitive grammatical cues, gender stereotype information is interpreted more flexibly for women than men. Similarly, a priming task showed a slower reaction time for feminine-stereotyped role nouns followed by masculine pronouns, but no parallel effect for masculine-stereotyped role nouns followed by feminine pronouns [@cacciari2007]. This asymmetry likely reflects that changes in gender norms over the last 50 years have consisted more of women being able to do masculine things than men being able to do feminine things.

Finally, in some contexts comprehenders interpret gender-mismatched pronouns as referring to an unknown, upcoming referent, instead of trying to establish coreference with a referent that does not agree in gender. Hearing pronouns that mismatched definitionally-gendered antecedents (e.g., *aunt...he*) elicited an [Nref]{#def-Nref .link-primary title="definition: Nref effect"} ERP response---a negative, left-frontal shift starting 300ms after the pronoun and continuing for the rest of the sentence [@nieuwland2014]. The authors argue this indexes a high degree of referential ambiguity, where the listener fails to match the pronoun to a referent. In this example, the Nref occurs if the listener assumes that because *aunt* and *he* mismatch in gender, *he* refers to someone not mentioned yet.

### 0.4.2 Generic Indefinite Singular *They* {#generic-indefinite}

The studies discussed so far show that comprehenders automatically[^0_introduction-3] and rapidly make inferences about gender when a new referent is mentioned---even when gender is irrelevant for comprehension---and that revising these gender inferences incurs [processing costs](#def-cost "processing cost"). Turning to singular *they*, the earliest published data compared the processing cost incurred by [generic indefinite](#def-generic-indefinite "generic indefinite singular they") singular *they* to those incurred by stereotype-mismatching *he* and *she* [@foertsch1997]. Participants read "should" statements using an [indefinite](#def-indefinite "indefinite") [antecedent](#def-antecedent "antecedent") and a pronoun, then decided whether or not they agreed:

[^0_introduction-3]: I make a distinction between our higher-level beliefs about gender and our lower-level, automatic cognitive processing. The fact that comprehenders immediately infer a gender categorization for new referents reflects statistical knowledge about how language is used, but does not necessarily reflect a belief in gender as binary and transparent. For a theory of how automatic categorization processes interact with higher-level beliefs about gender in the context of making gender attributions, see @friedman2014.

::: {#exm-foertsch .example-formatting}
\
1 A nurse should have an understanding of how a medication works\
2 even if he/she/they will not have any say in prescribing it\
3 because nurses must anticipate how a patient will respond to the medication.\
:::

The dependent measure was the time spent reading the clause including the pronoun (line 2 in [-@exm-foertsch]). There were four types of indefinite antecedents: stereotypically-masculine nouns, stereotypically-feminine nouns, gender-neutral nouns, and indefinite pronouns (e.g., *everyone*, *someone*); the four antecedents were crossed by three pronouns: *he*, *she*, and *they*. For gender-stereotyped antecedents, clauses with singular *they* were read more quickly than clauses with stereotype-mismatching pronouns and at the same speed as clauses with stereotype-matching pronouns. For gender-neutral antecedents, clauses with singular *they* were read at the same speed as clauses with *he* or *she*. For indefinite pronoun antecedents, clauses with singular *they* were read more quickly than clauses with *he* or *she*. The authors concluded that generic indefinite *they* was not more difficult to process than generic *he*, and in fact may be easier in some contexts.

An alternative baseline is a context where a plural mismatch effect is definitely expected. Instead of testing whether reading singular *they* is slower than *he* or *she* with singular antecedents like @foertsch1997, @sanford2007 tested if singular *they* retains the same plural mismatch effect as *he* and *she* with plural referents. Participants read sentences that included either a gender-unspecified indefinite antecedent (e.g., *a person*, *someone*) or a plural antecedent (e.g., *some people*), then either a singular pronoun (*him/her*) or a plural pronoun (*they*). This experiment employed an [eyetracking while reading](#def-eyetracking-reading "eyetracking while reading task") paradigm, which provides a more sensitive measure of processing disruptions than [self-paced reading](#def-SPR "self-paced reading task"). The analysis included measures of early processing, including go-past reading time, which is the total time spent looking at the critical region when first encountering it; and measures of later processing, including total reading time, which is the total time spent looking at the critical region the first time and any times returning to it. Early processing measures showed a plural mismatch effect for *him/her* (e.g., *some people...him* \> *a person...him*), but not for *their* (e.g., *a person...their* ≈ *some people...their*). The later processing measure showed plural mismatch effects for both him/her and their. However, the processing cost for singular *they* was small---only around 100ms. The authors interpret this to mean that singular pronouns show an earlier sensitivity to number mismatches than plural pronouns, but that when a mismatch is detected for singular *they*, it is easily accommodated.

### 0.4.3 Definite Singular *They* {#definite}

The early studies about comprehension of [indefinite](#def-indefinite "indefinite singular they") singular *they* by @foertsch1997 also tested [specific definite](#def-specific-definite "specific definite singular they") forms, using similar "should" statements, e.g., [-@exm-foertsch] with *my nurse* instead of *a nurse*. For masculine- and feminine-stereotyped antecedents, clauses with singular *they* showed intermediate reading times: faster than clauses with stereotype-mismatching pronouns, but slower than clauses with stereotype-matching pronouns. For gender-neutral antecedents, there was no difference between singular *they* and *he/she*. Across antecedent definiteness and gender stereotypicality, singular *they* only showed a penalty for definite, gender-stereotyped referents. Observing a processing cost for gender-stereotyped but not gender-neutral referents suggests that slower processing for definite specific singular *they* may be due more to expectations about when a speaker should know and mark the referent's gender, not necessarily due to number agreement [@foertsch1997].

A later study investigated reader's expectations about gender more directly [@doherty2017]. Participants read short stories that included a pronoun referring to a [definitionally-gendered](#def-definitional-gender "definitional gender") antecedent ("gender-known" condition, e.g., *spokeswoman*), a [stereotypically-gendered](#def-stereotypical-gender "stereotypical gender") antecedent ("high-expectancy" condition, e.g., *mechanic*), or a gender-neutral antecedent ("low-expectancy" condition, e.g., *cyclist*):

::: {#exm-doherty-conklin .example-formatting}
\
1 Adam recently had an accident in his car.\
2 He was emerging from a junction when he hit a cyclist and\
3 knocked him/her/them\
4 straight\
5 off the bike.\
6 Fortunately, the cyclist was not badly hurt.
:::

Participants' eye movements were analyzed over three regions at and immediately after the pronoun. For gender-neutral antecedents, singular *they* was not read faster or slower than *he/she*. For stereotypically-gendered and definitionally-gendered antecedents, singular *they* did show costs, and critically, these patterns were different between the two antecedent types. At the verb + pronoun region (line 3 in [-@exm-doherty-conklin]), singular *they* patterned with the gender-matching pronoun for definitionally-gendered antecedents (e.g., *spokeswoman...they* ≈ *spokeswoman...she*) but with the gender-mismatching pronoun for stereotypically-gendered antecedents (e.g., *mechanic...they* ≈ *mechanic...she*). At the adverb following the pronoun (line 4 in [-@exm-doherty-conklin]), singular *they* was not faster or slower compared to gender-matching *he/she* for either antecedent type. At the final region (line 5 in [-@exm-doherty-conklin]), singular *they* showed a cost compared to the gender-matching pronoun for definitionally-gendered, but not stereotypically-gendered antecedents. This is the reverse of the pattern seen at the verb + pronoun region, but now in the expected direction. However, Doherty & Conklin note that the cost of singular they is much more transient and less robust than the cost of a gender mismatch (e.g., *spokeswoman...he*). The fact that stereotypically-gendered and definitionally-gendered antecedents behaved differently, both in the eyetracking data and in the acceptability judgment task that was used to pilot the stimuli, is evidence for probabilistic gender expectations in discourse processing. In a later study, late-intermediate and advanced learners of English showed similar patterns of reading times, adding further evidence indicating that late acquisition of singular *they* is feasible [@speyer2019].

### 0.4.4 Singular *They* Coreferring with Proper Names {#names}

The findings so far show that when singular *they* refers to a [specific definite](#def-specific-definite "specific definite singular they")---but [gender-unspecified](#def-gender-unspecified "gender-unspecified singular they")---referent, it does incur a [processing cost](#def-cost "processing cost"), but one that is easily accommodated. The few studies about they coreferring with proper names (specific definite and [gender-specified](#def-gender-specified "gender-specified singular they")) also show a processing cost, but the magnitude and cause are still unclear. Early self-paced reading results have been inconclusive [@ackerman2018a; @ackerman2018b; @ackerman2020]. An [ERP](#def-ERP "ERP measures") study on people who used they/them pronouns for themselves or someone close to them---and thus were highly familiar with specific, gender-specified *they*---yielded mixed results [@prasad2020]. Participants showed no [P600](#def-P600 "P600 effect") effects, which index agreement and syntactic violations, for *themselves* coreferring with specific indefinite (e.g., *someone*) and specific definite gender-unspecified (e.g., *the participant*) referents, but did show P600 effects for specific definite gender-specified referents (e.g., proper names).

More recent preliminary findings showed that *they* coreferring with proper names elicited a P600 effect like gender-mismatching *he* and *she* (e.g., *Mary...he*), but only mismatching *he* and *she* elicited an [Nref](#def-Nref "Nref effect") effect. This suggests that singular *they* is causing some degree of grammatical processing difficulty for listeners, but that it is not causing referential failure like strong gender mismatches [@chen2023]. A related study used a [maze task]{#def-maze .link-primary title="definition: maze task"}, which presents participants with a sentence one word at a time, and at each word, they have to pick which of two words could continue the sentence grammatically. At the critical location, participants have to decide between a pronoun (*he*, *she*, plural *they*, or singular *they*) and a different part of speech that is not grammatical at that location, e.g., *Mary watched TV before bed because \[they or liked\]*, where a pronoun but not a verb can follow *because*. Participants were slower to decide that singular *they* could continue the sentence compared to gender-matching *he/she*, but not as slow as with gender-mismatching *he/she* (e.g., *Mary...she* \< *Mary...they* \< *Mary...he*) [@shenkar2023].

Finally, two sets of studies have investigated how comprehenders use discourse context to understand singular *they*, one using an offline comprehension question and one using mouse tracking. In the [offline comprehension](#def-offline "offline comprehension") task [@arnold2021], participants learned about three characters (1 he/him, 1 she/her, and 1 they/them), then read two-sentence stories with comprehension questions probing which character(s) they interpreted the pronoun as referring to. In the training phase, participants read stories with only one character, which strongly supported interpreting *they* as singular, e.g., [-@exm-arnold-1char]. In addition to seeing the character's pronouns modeled in the stories, some participants were given more direct information, e.g., *Alex uses they/them pronouns*. The majority of participants endorsed the singular interpretation (Alex is the one who fell down) during the training phase, and only participants who interpreted *they* as singular in all training trials were included in the primary analysis. After confirming that participants understood that the character uses they/them pronouns, the test phase investigated how *they* was interpreted in stories with two characters, where *they* could plausibly be singular or plural, e.g., [-@exm-arnold-2char-first].

::: {#exm-arnold-1char .example-formatting}
\
1-character context:\
"Alex went running. They fell down." Who fell down?
:::

::: {#exm-arnold-2char-first .example-formatting}
\
2-character context, named first:\
"Alex went running with Liz. They fell down." Who fell down?
:::

::: {#exm-arnold-2char-second .example-formatting}
\
2-character context, named second:\
"Liz went running with Alex. They fell down." Who fell down?
:::

Two factors increased the proportion of singular interpretations: direct information and discourse context. Among participants who had always chosen the singular interpretation in the one-character training trials, participants who had also been directly told that the character uses they/them pronouns were more likely to choose the singular interpretation in the two-character context. This demonstrates that people can learn about someone's pronouns and use that information to disambiguate singular from plural *they*. Participants were also more likely to choose the singular interpretation when the they/them character was named first ([-@exm-arnold-2char-first]) than when the they/them character was named second ([-@exm-arnold-2char-second]), which replicates prior findings for when *he* or *she* is ambiguous between two referents [@arnold2000; @arnold2007; @brown-schmidt2017; @gernsbacher1989] (see [Section 4.1](4_exp.qmd#motivation)).

In the [online comprehension](#def-online "online comprehension") task [@arnold2023], participants listened to stories about pairs of the characters interacting with objects:

::: {#exm-arnold-2char-online .example-formatting}
\
Liz and Alex were cleaning up after a dinner party. Liz handed a towel to Alex. Then they dried the plates.
:::

In the screen corresponding to [-@exm-arnold-2char-online], Liz is pictured with pots and pans, Alex is pictured with plates and silverware, and Alex and Liz together are pictured with cups and bowls. The participants' task was to click on the objects that the character in the final sentence was using, and their reaction time and the number of times their mouse movement changed direction horizontally (i.e., moving back and forth between options) were recorded. If participants understand that *they* is singular and refers to Alex, they would be able to anticipate which object to click on and respond faster after hearing *plates*. Unsurprisingly, participants were slower to click on the image for stories using singular *they* than *he* and *she*. However, the degree of processing cost was modulated by discourse context, like in the offline comprehension task. When the they/them character was mentioned first and was thus more likely to be the antecedent of the pronoun, the number of mouse direction shifts was not increased compared to *he* and *she*. The authors interpret this to mean that when the discourse context supports interpreting *they* as singular, listeners still understand it a bit more slowly, but are not experiencing additional competition between the singular and plural interpretations (i.e., moving their mouse between the images for Alex and Alex & Liz). These two experiments provide further evidence that any processing costs for gender-specified singular *they* are manageable for comprehenders. Moreover, demonstrating that the character being named first instead of second supports comprehending *they* as singular suggests that people are using similar cues to disambiguate between singular and plural *they* as when other pronouns are ambiguous. If this is the case, it points to successful integration of singular *they* into existing reference resolution mechanisms, instead of treating it as an exception.

## 0.5 Production {#production}

One line of research about the production of singular *they* situates it in sociolinguistic theories of politeness. @conrod2019 argues that gendered pronouns function much like honorific markers, reflecting and negotiating a social relationship, as opposed to encoding a static grammatical feature or making a claim about some biological reality. Singular *they* introduces additional options for speakers---including the [gender-unspecified](#def-gender-unspecified "gender-unspecified singular they") form for people who use he/him or she/her---and so the choice between these options carries information. Speakers can take a variety of approaches to this decision. Someone may prioritize quantity (including enough information) over relevance and quality (including only relevant and accurate information) [@grice1975]. In this case, the speaker could choose to be as specific as possible and use *he* or *she*, even when gender information is not relevant, or their use of *he* or *she* may be incorrect (e.g., the exchange in @exm-bright-sessions). If, on the other hand, the speaker prioritizes relevance over quantity, they could choose to be more vague and use *they*, even if they could include information about the person's gender. Similarly, if a speaker prioritizes quality over quantity, they could choose to use *they* when the person's gender is unknown, instead of making an inference about whether *he* or *she* would be correct (e.g., the exchange in @exm-tma1).

In addition to communicating information, conversations are also building social relationships. The politeness theory framework proposes that people need to maintain both positive face (being liked and confident) and negative face (being free from obligations and impositions), and what they say can either maintain or threaten their face [@brown1987]. @conrod2019 describes several face constraints for gendered pronouns: (1) *don't ungender*, because not specifying gender is an imposition on someone's positive face; (2) *don't misgender*, because specifying the wrong gender is an imposition on someone's positive face; and (3) *don't correct me*, because telling someone which pronouns to use is an imposition on their negative face. When a speaker does not know which pronouns to use, they can choose to prioritize (1) by making a guess, or to prioritize (2) by using gender-unspecified *they* or by avoiding pronouns. Much of the debate around pronouns is a conflict between (2) and (3), where people argue that correcting someone threatens face more than misgendering someone. Examples of this reasoning are discussed later in [Section 0.8](#sociopolitical-context "Sociopolitical Context"). Finally, choosing pronouns involves taking an affective and evaluative stance about both the person you are speaking about and the person you are speaking to [@dubois2007]. This stance-taking may be more overt, such as when speakers intentionally misgender someone to express disapproval and disagreement, or more subtle, such as when speakers leave gender unspecified to imply social distance [e.g., @conrod2019b].

Only a few experiments have tested language production. Generally, their preliminary findings indicate that speakers can produce [specific definite](#def-specific-definite "specific definite singular they") singular *they* in both writing [@kramer2021] and speech [@arnold2022], especially when shown examples of the person being referred to with they/them. Production appears to cluster into the same three patterns as acceptability judgments [@camilliere2021; @konnelly2020], with participants either not using singular *they* at all, using it only for referents introduced by last name (such that gender was unspecified), or using it for referents introduced with last names or first names (such that gender was inferrable) [@kaiser2023].

In addition to how speakers can learn to produce they/them pronouns for a person instead of he/him or she/her, another open question is how speakers integrate singular *they* into their production system when deciding to use a pronoun instead of a different type of referring expression. Since pronouns are the most reduced forms compared to proper names and noun phrases, speakers only tend to use pronouns when the [referent](#def-referent "referent") is highly salient, in focus, or accessible. In other words, speakers tend to choose the option that includes the least information if they think the comprehender already has enough information to identify the referent [@arnold2019]. The counter-argument to singular *they* being too ambiguous to understand is that standard pronouns like *he*, *she*, and plural *they* frequently have the potential to be ambiguous. Speakers already have strategies to avoid too much ambiguity, and comprehenders already have strategies to interpret ambiguous pronouns. If specific singular *they* is being successfully integrated into our language use, then speakers will use or adapt existing strategies to minimize ambiguity. In a corpus study of news articles about [nonbinary](#def-nonbinary "nonbinary") people who use they/them pronouns, writers were less likely to use pronouns overall for people who use they/them compared to people who use he/him or she/her. However, this difference was not explained by potential ambiguity, which the authors interpret to mean that writers may have been avoiding pronouns that were unfamiliar for them or their intended readers, not that a referent using they/them created contexts where a pronoun would have been uniquely ambiguous [@arnold2022a]. In a speech production study, participants were less likely to use a pronoun to continue a story that had introduced two characters than a story that had introduced only one character. Instead, people were more likely to use a name in this context since a pronoun could refer to two possible referents. However, pronoun use was reduced to the same degree for *they* compared to *he* and *she*, again suggesting that singular *they* does not introduce a unique level of ambiguity [@arnold2022].

## 0.6 Frequency {#frequency}

As society has become more accepting of LGBTQ+ identities, the [TGD](#def-TGD "trans and gender diverse") community in the United States has grown in both size and visibility. A meta-analysis of population-based, probability samples from 2006--2016 estimated that 1 in 250 U.S. adults are transgender [@meerwijk2017]. In 2014, the CDC Behavioral Risk Factor Surveillance System Survey---a representative, probability-based survey about the health behaviors and conditions of U.S. adults---added a set of demographic questions about sexuality and gender, which around 30 states now include. An average of 1 in 200 people have said they considered themself transgender [CDC, -@cdc2014; -@cdc2015; analyzed in @crissman2017; @herman2022], with the rate rising to 1 in 128 in the most recent survey [CDC, -@cdc2021]. The TGD community skews younger, even more so than the broader LGBTQ+ community [@harrison2012; @herman2022; @james2016; @streed2017]. While the sample sizes of population-based surveys of teens are smaller than those of adults, a larger proportion of U.S. teens identify as[^0_introduction-4] transgender---between 1 in 50 and 1 in 75 [CDC, -@cdc2019; @eisenberg2017; @herman2022; @kidd2021; @perez-brumer2017; @shields2013; @twenge2023].

[^0_introduction-4]: To be clear, I use language like "identify as" and "consider themself" not to imply that people's identities are less real, but to describe surveys asking people about the labels they use. Decisions about how to describe gender and sexuality are complicated and personal, and I want to maintain a distinction between the set of people who *do* say "yes, I am X," and the set of people who fall under the definition of X and *could* say "yes, I am X" or may be grouped as X in research analyses. Often in LGBTQ+ research the set of people who could identify as X is larger than the set of people who do identify as X, which makes estimating and talking about population sizes tricky.

An increasing proportion of the transgender community is [nonbinary](#def-nonbinary "nonbinary"): In 2014, 17% of transgender respondents in the CDC BRFSS survey did not identify as men or women; in 2021, this increased to 33% [CDC, -@cdc2014; -@cdc2021; similar or higher rates in @grant2011; @harrison2012; @james2016; @parks2023; @uk2018; @wilson2021]. The majority of the population-based surveys discussed so far ask if the person identifies as transgender, and then if so, if they are a man, a woman, or gender-nonconforming/something else. Since not all nonbinary people also identify as trans, the size of the broader TGD community is likely still underestimated [@james2016; @meerwijk2017; @wilson2021]. The U.S. Household Pulse survey, which asks American adults every few weeks about employment, living, and health conditions, added a survey question about gender in 2021. The response options include male, female, transgender, and none of these. While this is not the ideal way of asking about gender [NASEM, -@nasem2022], the data set is large enough that it is able to start correcting for the under-count of nonbinary people. Rates of nonbinary identity are increasing particularly for Gen Z adults (ages 18--26 in 2021 and 2022): 2.3% identify as trans and 3.3% as "none of these." To put this into perspective, out of the 39 million Gen Z adults in the U.S., about 2 million are trans and/or nonbinary, which is more than the population of Phoenix, AZ---the fifth-largest city [@twenge2023]. Analyzing changes in the Household Pulse survey over the past few years, Twenge argues that Gen Z represents a massive, ongoing generational shift in views about gender [-@twenge2023].

While the changes are largest in younger generations, support for and familiarity with TGD people has been growing across generational, political, and religious groups. Currently, 40% of U.S. adults know a trans person and 16% know a nonbinary person, and the proportion who have a trans family member or close friend has more than doubled from 11% in 2011 to 24% in 2019 [@jones2019; @minkin2021; PRRI, -@prri2021]. The majority (70%) say they would be somewhat or very comfortable learning that a friend, coworker, or community member was trans, and a slim majority (55%) say the same for their child [PRRI, -@prri2021]. On average, 60% of adults said they became more supportive of transgender rights between 2012 and 2019, compared to 25% who said they became less supportive. 40% said that trans people face "a lot of stigma or negative social judgment in their community" [@jones2019]. Among young adults specifically (ages 15--24), the majority (80%) said that there is a lot of discrimination against trans people, and only 12% perceived it as decreasing during 2017 [@jones2018].

Within the growing TGD community, around 80% of nonbinary people and 50% of trans people say that they use they/them pronouns [@cassian2021; @cassian2022; @cheung2020; @parks2023]. This corresponds to rapid increases in familiarity with singular *they* in recent years: Around 70% of people under 40, 60% of people 40--55, and just under 50% of people 55+ say they have heard a little or a lot about "people preferring that others use gender-neutral pronouns such as *they* instead of *he* or *she* when referring to them" [@parker2019]. 46% of people ages 18--29, 29% of people 30--49, 18% of people 50--64, and 11% of people 65+ personally know someone who prefers gender-neutral pronouns in 2021, up from 8--32% in 2018.[^0_introduction-5] Correspondingly, about 60% of people 18--29, 50% of people 30--64, and 40% of people 65+ say they would be somewhat or very comfortable using gender-neutral pronouns---which would most likely be singular *they*---for someone who asked. Political affiliation is a stronger predictor than age here, with 40% of Democrats saying they would be very comfortable and 40% of Republicans saying they would be very uncomfortable [@minkin2021]. Compared to gender-neutral pronoun use, U.S. adults are more divided about the concept of the gender binary, with 40% saying they somewhat or strongly believe there are a range of genders and 60% saying they somewhat or strongly believe there are only two [@jones2019; PRRI, -@prri2021; @twenge2023].

[^0_introduction-5]: Knowing a person who uses gender-neutral pronouns is more common than knowing a nonbinary person [@minkin2021; PRRI, -@prri2021], but this is not particularly surprising given that not all people who use gender-neutral pronouns are nonbinary, and that people may tell others what gendered language they prefer, without getting into the details of their gender identity.

## 0.7 Misgendering {#misgendering}

Despite these increases in visibility, [TGD](#def-TGD "trans and gender diverse") people in the U.S. continue to face high rates of discrimination and harassment in workplaces, schools, healthcare centers, and public spaces [@cruz2014; @grant2011; @james2016; @uk2018]; and are more likely to struggle with depression, anxiety, suicidality, and overall poor health than their [cisgender](#def-cis "cisgender") LGBQ+ peers and the general population [@bockting2013; @chodzen2019; @cruz2014; @eisenberg2017; @kattari2019; @perez-brumer2017; @streed2017]. For [nonbinary](#def-nonbinary "nonbinary") people specifically, health disparities and experiences of discrimination tend to be similar, or even worse, than other groups in the TGD community [@budge2014; @burgwal2019; @butler2019; @cheung2020; @clark2018; @harrison2012; @james2016; @kattari2020; @keuroghlian2015; @lagos2018; @lefevor2019; @morris2019; @newcomb2020; @sterzing2017; @tebbe2016; @veale2017b]. Recent work has contextualized these experiences in the [minority stress]{#def-minority-stress .link-primary title="definition: minority stress"} framework, where health disparities in a marginalized group arise from the array of stressors caused by societal stigma against them [@chodzen2019; @howe2019; @lindley2020; @puckett2020; @rood2016; @tebbe2016; @testa2015; @valentine2018; @whitehughto2015].

[Misgendering]{#def-misgendering .link-primary title="definition: misgendering"}---where someone is referred to using gendered language that does not match their identity---is a commonly reported minority stressor affecting the TGD community. TGD people describe being misgendered as alienating, devaluing, invalidating, and painful [@cordoba2020; @goldberg2019; @gunn2020; @johnson2019; @pitcher2017; @saltzburg2010; @truszczynski2020]. This is because the language we use to refer to ourselves---names, pronouns, kinship roles, community affiliations---creates and reflects parts of our identity:

> If, as posited by social constructionism, language constitutes and creates the meaning of our lives, then not having language to fit how \[genderqueer youth\] view themselves leaves them feeling outside of and "not counted" in the human experience...It seems that in trying to fit gender variant young people into a languaged existence that does not correspond to how they view themselves, society deprives them of sense of self, self-value, and a recognized social existence.\
> --- @saltzburg2010

As a consequence of having their identities forgotten, contested, or overwritten, people who are misgendered more frequently show higher rates of depression, stress, suicidality, disordered eating, body dissatisfaction, and low self-esteem [@galupo2020; @mclemore2015; @mclemore2018; @mitchell2021; @trevorproject2020]. Using gender-affirming pronouns, names, and body terms is particularly important in healthcare contexts, as it forms a key part of how positive or negative the experience is for TGD patients [@baldwin2018].

Nonbinary TGD people are misgendered frequently: only 1 in 10 nonbinary youth report all or most people respecting their pronouns [@trevorproject2020], and 2 in 3 nonbinary people did not ask for correct pronouns at work to avoid discrimination [@james2016]. Additionally, some studies report that getting people to use new pronouns is more difficult than getting people to use a new name [@barbee2019]. While most studies about misgendering report participants' genders, but not the gendered language they use, the fact that a large proportion of nonbinary people use they/them pronouns [@cassian2021; @cassian2022; @cheung2020; @parks2023]---combined with the relative newness of [specific](#def-specific-definite "specific definite singular they") singular *they*---means we can infer that people who use they/them pronouns are likely misgendered regularly.

Using they/them pronouns often places TGD people in a double bind, where they are forced to choose between experiencing more discrimination by openly identifying as TGD, or between getting misgendered. For example, when searching for jobs, the majority of nonbinary people said that identifying themselves as nonbinary to a potential employer would hurt their job search somewhat (60%) or very much (25%). These expectations were confirmed by an experiment that measured how adding they/them pronouns to a resume affected application outcomes. The otherwise-identical resume received 9% more interest, and when asked directly about their impressions, hiring managers rated the applicant with a resume including they/them pronouns as 7% less qualified and were 4% less likely to invite them for an additional interview [@mcgonagill2023].

Misgendering is a form of [microaggression]{#def-microaggression .link-primary title="definition: microaggression"} [@chang2015; @nadal2014; @nadal2016; @nadal2019]. In the original microaggression framework, developed to describe experiences with racism, microaggressions fall into three categories: microinsults, which carry subtle or implied snubs (i.e., that the speaker did not expect the person to be as competent as they are); microassaults, which insult someone through name-calling or avoidant behavior; and microinvalidations, which deny the experience, beliefs, or emotions of the person (i.e., "but I don't see color" as negating someone's experience of how their race affects how they are treated) [@sue2007]. Intentional misgendering---where someone deliberately uses the wrong name or pronouns to insult someone or deny the legitimacy of their identity---would fall under the category of microassaults [@conrod2019b; @nadal2013]. Unintentional misgendering---where someone uses the wrong name or pronouns because of an incorrect inference about someone they don't know (i.e., that all people they perceive as feminine use she/her) or because of a speech error after someone changes names or pronouns---would fall more under the category of microinvalidations [@gunn2020; @mclemore2015]. The key idea of the microaggressions framework is that while many individual events may be minor or perpetrated unintentionally, the toll of experiencing them frequently is substantial and cumulative. Nonbinary people described their reactions to being misgendered using similar distinctions as the microaggressions framework, where both the perceived intent and the proximity of the speaker mattered [@cordoba2020]. Being misgendered by people they were close to was interpreted as more intentional and experienced as more hurtful. While being misgendered by acquaintances or strangers was interpreted as less intentional and hurt less, these negative experiences accumulate constantly. One genderqueer person described their experience as:

> But sometimes it just feels like a thousand paper cuts. And you know, by the end of the day you're like, "how many times has someone misgendered me today?" It's really difficult to speak about someone without using a pronoun, particularly when you're not aware that's a problem. And so, sometimes by the end of the day you just feel like, you've just been rubbed raw and you're like, "How many billions of times did someone refer to me as she and Ms. today?"\
> --- interviewed in @cordoba2020

Other work has described how social support can mitigate the negative mental health effects of misgendering and other transphobic microaggressions [@bockting2013; @mclemore2015; @penklis2020; @puckett2019; @testa2015; @trevorproject2020; @veale2017a; @weinhardt2019]. Little research, however, has focused on preventative strategies. Reducing how often TGD people are misgendered is one avenue for ameliorating disparities in mental health.

## 0.8 Sociopolitical Context {#sociopolitical-context}

Like other language innovations in the LGBTQ+ community, singular *they* evokes overt hostility about [nonbinary](#def-nonbinary "nonbinary") and transgender identities, language change, and people's right to determine how they are referred to. More broadly, [misgendering](#def-misgendering "misgendering") and language reform have become a prominent topic in the "political correctness" and "wokeness" wars. A Wall Street Journal op-ed by journalist and political speechwriter Peggy Noonan expresses the major themes of opposition:

> I've been thinking about the language and behavioral directives that have been coming at us from the social and sexual justice warriors who are renaming things and attempting to control the language in America. In one way it's the nonsense we've all grown used to, but it should be said that there's an aspect of self-infatuation, of arrogance, in telling people they must reorder the common language to suit your ideological preferences. There is something mad in thinking you should control the names of things...Offices and schools are forced to grapple with all the new gender-neutral pronouns...Use "they" a lot. It's gender neutral...This is grammatically incorrect but so what? Correct grammar, and the intelligibility it allows, is a small price to pay for inclusion and equality. We are being asked to memorize all this, to change hundreds of years of grammar and usage, to accommodate the needs or demands of a group that perceives itself as beleaguered.\
> --- "What were Robespierre's Pronouns?" [-@noonan2019]

On its face, the opposition to singular *they* is about grammatical correctness and clarity, presuming that English grammar exists in some pure form which must be guarded and preserved. While some people claim that "correct" grammar cannot change, others argue that change is simply too difficult a request. For people like Noonan, the costs of changing language use are massive, and the costs of misgendering others are grossly exaggerated.[^0_introduction-6] Arguments about grammar frequently mask arguments about gender: are nonbinary identities real and important enough to warrant consideration in our language use? Noonan implies that they are not when she dismisses TGD people as "a group that perceives itself as beleaguered." Former academic social psychologist turned conservative influencer Jordan Peterson is more overt about opposing TGD identities more than he supports traditional grammar:

[^0_introduction-6]: See @conrod2019's analysis of politeness, discussed in [Section 0.5](#production).

> I don't recognize another person's right to decide what words I'm going to use, especially when the words they want me to use, first of all, are non-standard elements of the English language and they are constructs of a small coterie of ideologically motivated people. They might have a point but I'm not going to say their words for them...There's not enough evidence to make the case that gender identity and biological sexuality are independently varying constructs. I don't believe that it's reasonable for our society to undermine the entire concept of binary gender in order to hypothetically accommodate a tiny minority of people.\
> --- "I'm not a bigot" Meet the U of T prof who refuses to use genderless pronouns [-@peterson2016]

I have already presented population data showing that the TGD community is not so tiny of a minority that they are not, practically speaking, worth consideration ([Section 0.6](#frequency "Frequency")). More importantly, the clinical evidence shows that misgendering causes harm ([Section 0.7](#misgendering "Misgendering")). One of the premises of this dissertation is that getting someone's pronouns right is not a unique or unreasonable demand. Instead, I place pronouns in the same category as names and titles, where we generally do agree that people get to "decide what words \[other people\] are going to use." In some cases, it may be linguistically difficult, like how someone's name may be hard to pronounce for non-native speakers, but doing our best to get it right is part of being polite.

While the debate about singular *they* and nonbinary identities is relatively recent, the broader debate about gendered language, sociopolitical influences on language, and the standards of correct speech has been happening for centuries [@bodine1975]. The following 1880 complaint about generic *they* as an alternative to generic *he* bears striking similarity to Noonan's complaints about singular *they*:

> *Their* is very commonly misused with reference to a singular noun. Even John Ruskin has written such a sentence as this: "But if a customer wishes you to injure their foot or to disfigure it, you are to refuse their pleasure." How Mr. Ruskin could have written such a sentence as that (for plainly there is no slip of the pen or result of imperfect interlinear correction in it), or how, it having been written, it could be passed by an intelligent proof-reader, I cannot surmise. It is, perhaps, an exemplification of the straits to which we are driven by the lack of a pronoun of common gender meaning both *he* and *she*, *his* and *her*. But, admitting this lack, the fact remains that *his* is the representative pronoun, as mankind includes both men and women.\
> --- *Everyday English* [-@white1880]

Complaints about singular *they* and *he or she* as alternatives to generic *he* were essentially the same: they were argued to be grammatically incorrect and unclear, despite common usage [@bodine1975]. More critically, non-sexist language reform was considered unnecessary [@blaubergs1980; @martyna1980; @parks1998]. Women's opposition to using generic masculine language was trivial and unreasonable, a statement that is far more political than linguistic [@ehrlich1992; @penelope1982]. In each of these arguments, the underlying assumption is that the status quo and defense of it is not ideologically motivated, but support for language change is.

This dissertation takes it for granted that people asking to have their identities respected and to not be misgendered is not, as the subtitle of Noonan's essay claims, "the work of sociopaths who politicize language" [-@noonan2019]. Unfortunately, pronouns have become an overt symbol of whether or not you acknowledge that trans and gender diverse people exist, with "using pronouns" escalating from a dog whistle to one of the focuses of current anti-LGBTQ+ legislation. 2023 has already seen a record number of bills introduced in U.S. state legislatures targeting transgender rights [HRC, -@hrc2023]. Many of these bills include policies about misgendering---alongside more extreme policies such as outlawing all gender-affirming medical care [ACLU, -@aclu2023]. The majority of the current bills focus on public school contexts and minors. Multiple states have successfully banned [TN @tn2023] or attempted to ban [AZ @az2022; IN @in2023a; ND @nd2023b] public schools from requiring that employees refer to a student using pronouns different than he/him or she/her corresponding to the student's [sex assigned at birth](#def-SAB "sex assigned at birth").[^0_introduction-7] The proposed legislation frequently moves beyond banning consequences for misgendering to banning the promotion of not misgendering [IN @in2023a]. For example, one Oklahoma bill bans "creating, enforcing, or endorsing a policy that respects, favors, endorses, or promotes non-secular self-asserted sex-based identity narratives or sexual orientation orthodoxy." This includes "mandating non-obvious pronoun changes that respect gender identity ideology and sexual orientation orthodoxy" because these are "naked assertions that are implicitly religious and have a tendency to erode community standards of decency and promote licentiousness" [OK @ok2023].[^0_introduction-8]

[^0_introduction-7]: As of May 30, 2023, the Indiana bill is dead, the Arizona and North Dakota bills were vetoed by the governor, and the Tennessee bill was signed into law.

[^0_introduction-8]: Advancing as of May 30, 2023.

The prohibition of promoting not misgendering often moves to creating consequences for not misgendering. In most variations of this bill, school employees would not be allowed to use a student's chosen pronouns unless the school has written permission from a parent [AZ @az2022; IN @in2023a; ND @nd2023a; @nd2023b; NH @nh2023; OK @ok2022],[^0_introduction-9] as well as medical documentation for diagnosed gender dysphoria [IN @in2023a]. This would make it difficult for TGD students to be out at school without proactive support from a parent, which many teenagers do not have [@baum2012; @trevorproject2020; @trevorproject2022]. Instead, school employees would be legally required to notify parents if student uses "expresses or indicates a desire to change...(A) name; (B) attire; or (C) pronoun, title or word to identify the student; in a manner that is inconsistent with the student's biological sex assigned at birth" [IN @in2023b].[^0_introduction-10] In 2022, only half of TGD youth said their school was supportive, but only a third said their home was supportive [@trevorproject2022]. This indicates that while schools are not supportive enough overall, they are still an environment where many TGD youth receive support that they are not otherwise receiving at home---a possibility that the current legislation aims to remove.

[^0_introduction-9]: As of May 23, 2023, the Indiana and New Hampshire bills are dead, the Oklahoma bill is advancing, and the Arizona and North Dakota bills were vetoed by the governor.

[^0_introduction-10]: Dead as of May 23, 2023.

Anti-LGBTQ legislation also targets education more broadly, not just policies about specific transgender students. Schools would not be allowed to provide instruction "recognizing expressed gender" in classrooms or in professional development [ND @nd2023b], or to teach "different pronouns other than those in common use in the English language when referring to the male or female" [NH @nh2023]. Books that "promote gender fluidity or gender pronouns" would be in the category of books that parents could report and have removed from schools [AZ @az2023].[^0_introduction-11]

[^0_introduction-11]: As of May 23, 2023, the North Dakota bills are vetoed and not advanced to a full vote, respectively. The Arizona bill has passed the senate and is being considered by the house.

Why talk about pronouns now? Given how legal protections and healthcare access are being eroded in the U.S., misgendering is far from the most immediate or severe hardship facing trans and gender diverse people. A similar argument was made in the non-sexist language debates [@blaubergs1980; @parks1998], and probably comes up in every language reform effort. Claiming that misgendering is worth addressing is not claiming that language is the worst problem, and a form of injustice does not need to be one of the most severe to be worth fighting. Much as we might like to ignore gendered language in favor of other, bigger problems---or at least people who aren't linguists might like to think less about language---English does not give us the option of ignoring it. Because Standard English requires us to encode gender in many of the pronouns, titles, and other terms we use to refer to people, gender is part of "thinking for speaking" [@slobin1996], where we have to think about and assert gender even in contexts where we might otherwise prefer not to. In the words of one genderqueer trans person:

> I think gender becomes very prominent when you are constantly being misgendered, and living with dysphoria. I don't necessarily want it to be important, but it is in the way I guess an injury is important, in that you have to be careful with it, pay it more mind than a non-injured part...I really wish it didn't have to be, wish it wasn't enshrined in our language that people's gender is the most important thing and the first thing we need to know, even for a casual "hello." --- interviewed in @cordoba2020

A second reason that misgendering is important to address now is that it is a tractable and winnable problem. The debates about misgendering are headed by a small but vocal minority. As I discussed in [Section 0.6](#frequency "Frequency"), the majority of people are supportive and open to learning. Critically, misgendering is one aspect that individual allies have the ability to concretely affect. While most people cannot, for example, change healthcare policy in their state, they can change their own language and the norms of their communities, making their environments more welcoming to the trans and gender diverse people in their communities. Singular *they* is a case where linguistics and cognitive psychology have relevant expertise and an opportunity to contribute to socially relevant research.
