project:
  type: book
  execute-dir: project
  output-dir: docs

book:
  # Metadata
  title: "Learning to comprehend and produce singular <i>they</i><br>"
  date: "06/15/2023"
  available-date: "08/01/2023"
  author:
    - name: Bethany Gardner
      orcid: 0000-0002-5154-2040
      email: bethany.gardner@vanderbilt.edu
  # doi:

  # Structure
  chapters:
    - index.qmd
    - 0_abstract.qmd
    - 0_introduction.qmd
    - part: Experiments
      chapters:
        - 1_exp.qmd
        - 2_exp.qmd
        - 3_exp.qmd
        - 4_exp.qmd
    - 5_general_discussion.qmd
  appendices:
    - 6_supplementary_analyses.qmd
    - 7_references.qmd

  # Links/tools
  repo-url: https://github.com/bethanyhgardner/dissertation
  sidebar:
    tools:
      - icon: person-circle
        text: "About Me"
        href: https://bethanyhgardner.github.io/
      - icon: enve;ope
        text: "Contact"
        href: "mailto: bethany.gardner@vanderbilt.edu"
      # - icon: filetype-pdf
      #  text: "Download"
      #  href: https://placeholder-to-proquest
    search: true
    style: docked
    foreground: "#7570B3"
    background: "#ededed"
  page-footer:
    center:
      - text: "&copy; 2023 Bethany Gardner"

# References
bibliography: resources/references.bib
csl: resources/formatting/apa.csl
link-citations: true
link-bibliography: true


# Other citation info
citation:
  title: Learning to comprehend and produce singular \emph{they}
  author:
    - name: Bethany Gardner
      orcid: 0000-0002-5154-2040
      email: bethany.gardner@vanderbilt.edu
      affiliation:
      - name: Vanderbilt University
        department: Department of Psychology & Human Development
        city: Nashville
        state: TN
  type: thesis
  genre: Doctoral dissertation
  publisher: Vanderbilt University
google-scholar: true

copyright:
  holder: Bethany Gardner
  year: 2023

appendix-cite-as: display

# Rendering
format:
  html:
    execute:
      echo: false
      output: false
    theme: pulse
    css: resources/formatting/pulse_modified.css
    mainfont: Arial
    monofont: Arial
    embed-resources: true
    number-depth: 3
    toc-expand: 2
    toc-depth: 4
    fig-align: left
    fig-dpi: 300
    fig-width: 6.5
    tbl-cap-location: top

knitr:
  opts_chunk:
    out.width: "80%"
