# General Discussion {.unnumbered}

Using singular *they* when a [referent's](introduction.qmd#def-referent "referent") gender is unknown or unspecified has become increasingly common and accepted by U.S. English speakers in recent years. Using they/them pronouns is not exclusive to [nonbinary](introduction.qmd#def-nonbinary "nonbinary") people, but it is a particularly common choice for them, since singular *they* is the most common gender-neutral alternative to he/him and she/her [@cassian2021; @cassian2022; @cheung2020; @parks2023]. The majority of U.S. adults (50--70% across age groups) know at least a little about people using they/them pronouns, and 11--46% personally know someone who uses they/them in 2021, up from 8--32% in 2018. While these proportions are highest in younger generations, they have been increasing across all generations, as well as across political affiliations and religious groups [@minkin2021; @parker2019]. This increase in familiarity with gender-neutral pronouns corresponds to increases in both the visibility and the size of the [trans and gender diverse (TGD)](introduction.qmd#def-TGD "TGD") community. Estimates based on probability-sampling surveys suggest that 1 in 200 adults in the U.S. consider themselves^[4](introduction.qmd#fn-ref4)^ transgender [@crissman2017; @herman2022; @meerwijk2017]. This number has been increasing since the mid-2010s [CDC, -@cdc2021], especially as population-based surveys are changing their question designs to recognize nonbinary people who fall under the TGD umbrella, but may not also identify as transgender. Among Gen Z adults (ages 18--26 in 2021 and 2022), 2.3% identify as trans and 3.3% as *none of these* (out of *man*, *woman*, *transgender*), which corresponds to the population of the fifth-largest city in the U.S. [@twenge2023].

The backlash to an increasing number of teens and young adults openly expressing TGD identities has been severe. 2023 has seen a record number of bills introduced in U.S. state legislatures targeting healthcare for, civil rights protections for, and education about TGD people [@hrc2023]. Many of these bills include policies preventing people from respecting that someone has changed their pronouns, particularly in educational contexts [e.g., the recently-passed TN @tn2023]. "Using pronouns" has become a symbol of whether or not you acknowledge and respect TGD people's existence. Indeed, people describe being [misgendered](introduction.qmd#def-misgendering "misgendering") as alienating, devaluing, invalidating, and painful [@cordoba2020; @goldberg2019; @gunn2020; @johnson2019; @pitcher2017; @saltzburg2010; @truszczynski2020], and people who are misgendered more frequently show higher rates of depression, stress, suicidality, disordered eating, body dissatisfaction, and low self-esteem [@galupo2020; @mclemore2015; @mclemore2018; @mitchell2021; @trevorproject2020].

However, this opposition represents a loud minority. Many people are open to learning: across age groups, 40--60% of U.S. adults say they would be somewhat or very comfortable using a gender-neutral pronoun for someone who asked [@minkin2021]. Still, learning a new language form can be hard, and many people continue to make errors, despite supportive intentions. This often results in seemingly-counterintuitive errors like "she uses they/them pronouns" (e.g., @exm-lovato). I began by arguing that errors like these occur because learning to use they/them pronouns requires a change in pronoun production processes. Instead of selecting pronouns based on morphosyntactic gender features of a name [e.g., @schmitt1999] or based on [semantic/conceptual gender](introduction.qmd#def-conceptual-gender "conceptual gender") features of a person [e.g., @anton-mendez2010], speakers may need to retrieve an episodic memory of a person's stated pronouns or the pronouns they have observed other speakers using in reference to that person. To that end, this dissertation investigated how people learn to associate pronouns with a person, how they use that information in language production and comprehension, and what factors can support learning.

Experiment 1 demonstrated that speakers can learn to associate pronouns with a person, in a context where the use of they/them could not be predicted from the name. While explicit memory for a person's pronouns strongly predicted accurate production, it did not guarantee it. In Experiment 2, reading a brief PSA about gendered language increased the proportion of speakers who produced singular *they* at least once and their accuracy when doing so---arguably by motivating participants to pay more attention to information about the character's pronouns during the introductions, then to attempt to retrieve the information later during the sentence completion task. Experiment 3 then showed that when information about a person's pronouns is made more salient by directly stating it during introductions and made more available by including it on nametags, speakers can and do use this information to correctly produce singular *they*. These results all support a model where speakers can use episodic memory for a person's stated pronouns to select which pronoun to produce, behavior that is not accounted for in current processing models.

One of the primary focuses of research on pronoun production has been *when* speakers choose to use pronouns instead of other referring expressions [@arnold2019], but the subsequent choice of *which* pronoun to use is less well understood. If applied to proper names and pronouns referring to people, production models either assume that speakers select pronouns based on morphosyntactic features of the name, or based on semantic/conceptual features of a person. As an example of the first approach, Schmitt et al.'s [-@schmitt1999] model of lexical access in pronoun production argues that if a lexical concept is activated and sufficiently "in focus" in the discourse, the speaker will produce a pronoun instead of a full noun phrase. In this model, tested with object labels in German, activating the lexical concept for the noun also activates the corresponding [grammatical gender](introduction.qmd#def-grammatical-gender "grammatical gender") node (masculine, feminine, or neuter). If the speaker uses a pronoun, the gender node is selected in order to produce the correct pronoun [@jescheniak1994; @levelt1999; @roelofs1992]. When producing gender-marked pronouns or determiners, competition between different forms can arise from the grammatical gender features of other lexical concepts that are also activated [@schiller2003]. If each lexical concept can only correctly be associated with a single grammatical gender, models of grammatical gender selection may not need to include competition between multiple grammatical gender features activated by the same lexical concept. The closest analogue may be languages where the singular and plural forms of determiners vary for the same grammatical gender, and one approach argues that the singular form is activated by default and can interfere with activating the plural form [@jescheniak2014; @schriefers2002].

In models of grammatical gender processing, it is reasonable to assume that once a speaker decides to produce a pronoun, there is typically only one correct pronoun to use. If extended from pronouns referring to objects to third person gendered pronouns referring to people, Schmitt et al.'s model might predict that the lexical entry for a masculine name would automatically activate the masculine gender node, which is linked to he/him pronouns, and the lexical entry for a feminine name would automatically activate the feminine gender node, which is linked to she/her pronouns. However, this approach would need to be modified to account for how speakers use singular *they*. One option would be to add a neutral gender node,[^general_discussion-1] which is linked to singular they/them pronouns. The lexical entry for a name could activate the neutral gender node, in addition to or instead of the masculine or feminine nodes. This is similar to how Konnelly & Cowper's morphosyntax model of gender agreement (described in [Section 0.3](#acceptability)) could function in a processing model. They propose that "innovative" speakers, who only accept [specific definite](introduction.qmd#def-specific-definite "specific definite singular they") antecedents for singular *they* that are [gender-unspecified](introduction.qmd#def-gender-unspecified "gender-unspecified singular they"), can accommodate a proper name by adding a new lexical entry for the name that does not have a masculine or feminine feature [-@konnelly2020].

[^general_discussion-1]: A related question is if the model would need separate nodes for gender-unspecified and gender-specified singular *they*. But since the experiments here only elicit gender-specified *they*, I focus on that form.

This gets us closer to accounting for the use of singular *they* in the current experiments by allowing a name to activate multiple gender nodes. In Experiments 1 & 2, the masculine names would activate the masculine gender node and possibly also the neutral gender node, and the feminine names would activate the feminine gender node and possibly also the neutral gender node. If the neutral gender node is activated, it is presumably in competition with the masculine or feminine node, with speakers trying to use *they* instead of defaulting to *he* or *she*. However, it is clear that speakers are using more than the lexical information for proper names to select pronouns. None of the current experiments tested a context where names provided enough information to predict pronouns, such as a set of characters where everyone with masculine names used he/him, everyone with feminine names used she/her, and everyone with gender-neutral names used they/them. Instead, Experiments 1 & 2 only used masculine and feminine names, with one third of the characters using they/them and the other two thirds using the expected he/him or she/her. Experiment 3 used all gender-neutral names, where the use of he/him, she/her, or they/them could not be predicted from the name. In both contexts, using singular *they* required information in addition to the lexical features or knowledge about gender distributions associated with the name. Participants had to associate they/them with the particular character, i.e., *this* Alex, not all Alex's in general.

Instead of proposing that pronouns are selected via lexical information associated with the name, pronoun production models can assume that speakers select pronouns based on semantic or conceptual information about the person's gender [@ackerman2019]. Here, psycholinguistics research has mostly focused on errors in adult second language learning. For example, English possessive pronouns agree with the possessor (e.g., in *Jaime gave the apple to their brother*, the pronoun agrees with *Jaime*), which can result in errors by native speakers of languages where possessive pronouns agree with the possessee (e.g., the pronoun would agree with *brother* instead of *Jaime*) [@pozzan2017]. This is more of an issue about which person the pronoun agrees with, not which gendered form should be selected for the person. Other experiments have looked at errors by native speakers of languages that do not mark gender in third-person singular pronouns, such as Finnish and spoken Mandarin Chinese [@pozzan2017; @siewierska2013]. This results in errors between he/him and she/her, where it is assumed that the speaker has the correct inference about the person's gender, but not a consistent mapping between gender categories and which pronouns to produce[^general_discussion-2] [@ackerman2019], since it is not information their native language requires them to encode [@slobin1996].

[^general_discussion-2]: Accounts of grammatical gender errors assume the opposite. Grammatical gender marking errors remain common even in highly-proficient learners, particularly if they are native speakers of a language without grammatical gender (e.g., English speakers learning Spanish) [@anton-mendez2010; @gruter2012]. These errors occur when a speaker selects the wrong grammatical gender feature for a word, then produces the pronoun corresponding to that wrong grammatical gender category.

An approach where speakers select pronouns based on semantic or conceptual information about the person's gender can better account for they/them pronouns, particularly if you assume that information about a person's pronouns could be encoded as part of conceptual gender. Traditional approaches treat conceptual gender as primarily automatic inferences (see the mismatching gender stereotype experiments discussed in [Section 0.4.1](#gender-agreement)), but one option is to assume episodic information can be added. If someone states that they use they/them pronouns or other speakers are using they/them pronouns for them, this could prompt a revision of the original gender inference that directed to he/him or she/her.[^general_discussion-3] This model would also need to be modified to account for multiple pronouns being associated with a person, instead of having a one conceptual gender inference to one set of pronouns mapping. Speakers often alternate between they/them and he/him or she/her, like the errors in these experiments or in the Demi Lovato article [@towers2021]. Alternating between pronouns can also be intentional when referring to people who accept multiple pronouns [e.g., @gurley2021; @monae2022]. A one-to-one model also does not account for [gender-unspecified](introduction.qmd#def-gender-unspecified "gender-unspecified singular they") [specific](introduction.qmd#def-specific "specific referents") singular *they*, particularly when it is used when the speaker *does* know the referent's gender, but does not include that information. In this case, the conceptual gender information is not driving pronoun selection, because the speaker is choosing to not specify gender. Overall, the behavior of participants producing singular *they* in the first three experiments demonstrates that speakers are incorporating additional sources of information and choosing between more options than are accounted for by existing processing models, where pronouns are selected based on the lexical information connected to the name or the gender categorization connected to the person.

[^general_discussion-3]: Here, I can only claim that information about gendered language forms is added to knowledge about a person, which could but does not necessarily correspond to changing an underlying gender categorization. See @friedman2014 for a theoretical model and behavioral data about how people revise their original automatic categorizations of a person's gender.

Experiment 4 turned from production to comprehension, but with the same underlying question: [specific definite](introduction.qmd#def-specific-definite "specific definite singular they") singular *they* does show a [processing cost](introduction.qmd#def-cost "processing costs") compared to *he* and *she*, but it is still unclear how large and how persistent those costs are, and how singular *they* is fitting into the existing processing mechanisms comprehenders have for *he* and *she*. Results from a visual world study showed that, in a context where participants could come to expect certain characters to be referred to with they/them, listeners were able to use singular *they* to identify the referent, just to a lesser degree than with *he* and *she*. This resembles patterns seen in young children [@arnold2007; @song2005] and in adult second language learners [@cunnings2017; @gruter2012; @speyer2019]. One open question is how these findings will replicate in future years as people continue to gain experience with using they/them pronouns, and if the learning trajectory will be similar to those observed for other pronouns during language development and second language acquisition.

Unlike prior findings for when *he* or *she* is ambiguous between two referents [@arnold2000; @arnold2007; @brown-schmidt2017; @falandays2020] and preliminary findings for singular *they* using a different task [@arnold2023], participants in Experiment 4 did not show an order of mention effect for singular *they*. The pronouns in these stories can refer to either of the two named characters, but is more likely to refer to the character named first than the character named second [@gernsbacher1989; @kaiser2011]. Listeners can use this information to help disambiguate the referent, and thus start looking at the target character---which the [visual world paradigm](exp4.qmd#def-VWP "visual world paradigm") takes to mean that they understand who the sentence is referring to---earlier for characters mentioned first. This pattern was not observed in *they* trials. The third finding in Experiment 4 was that after hearing *he* or *she*, listeners were more likely to be looking at the target character if the competitor character used she/her or he/him than if the competitor character used they/them. The lack of an order of mention effect and the observation that they/them characters behaved differently as competitors than he/him and she/her characters both suggest that while listeners can successfully comprehend *they* as singular, they may be using different strategies to do so, leaving a number of follow-up research questions.

I want to emphasize here that the processing cost for singular *they* is large enough to be statistically significant and relevant for understanding language processing mechanisms, but that this does not necessarily correspond to meaningful differences in processing fluency---people's subjective experience of how easy it was to understand the story [@alter2009]. In this experiment, visual inspection of the data shows that around 50% of participants were looking at the target character half a second after the onset of *he* or *she*, compared to around 35% half a second after the onset of *they* (@fig-exp4-3panel). Similarly, in one reading time study, indefinite gender-unspecified *they* (e.g., *a person, someone*) took about 100ms longer than *he* and *she*, which the authors note is a smaller, more easily accommodated processing cost than other types of gender and number agreement mismatches [@sanford2007] (see [Section 0.4.2](#generic-indefinite)). The processing fluency account predicts that language that is more difficult to understand elicits more negative attitudes about the speaker [@dragojevic2016; @dragojevic2017; @dragojevic2020] (see [Section 4.1](exp4.qmd#motivation)). However, it is an open question how processing costs in psycholinguistics measures correspond to processing fluency---how the time course in a visual world study matches how hard a listener consciously perceives singular *they*. Like Sanford & Filik I would argue that, when compared to the processing costs seen in other experiments, the processing costs observed here with singular *they* are within the range that comprehenders can normally accommodate. Instead of singular *they* being dramatically or permanently more difficult to understand, reference resolution is already complicated and ambiguous, even in contexts that are less socio-politically marked.

From a theoretical perspective, the four experiments in this dissertation demonstrate how singular *they* pushes language processing models to incorporate additional factors---especially social ones---to account for the full range of people's language use. From a practical perspective, these experiments show that while learning singular *they* is hard, it *is* doable. Multiple strategies can support learning, including providing information about why paying attention to gendered language is important, showing examples of singular *they* in use, making information about pronouns more salient by including it in introductions, and making information about pronouns more accessible by including it in places like nametags and display names. Learning to use they/them pronouns is worthwhile, because misgendering is a key aspect of how respected and welcome trans and gender diverse people feel in a community, and reducing misgendering is something that individual allies have the opportunity to concretely change.
